@endpoint = http://localhost:3000/api/v1/cars

###
# @name postACar
POST {{endpoint}} HTTP/1.1
content-Type: application/json
x-api-key: blahblah

{
    "make": "Toyota",
    "model": "Supra"
}
###
@newCar = {{postACar.response.body._id}}

###
GET  {{endpoint}}/{{newCar}} HTTP/1.1
content-type: application/json


###

DELETE  {{endpoint}}/{{newCar}} HTTP/1.1
content-type: application/json

###

PUT  {{endpoint}}/{{newCar}} HTTP/1.1
content-type: application/json
x-api-key: blahblah

